---

- name: Create docker service override directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    recurse: yes
  when:
    - not skip_docker_service_override

- name: Install docker override file
  template:
    src: override.conf.j2
    dest: "/etc/systemd/system/docker.service.d/override.conf"
    backup: no
    owner: root
    group: root
    mode: 0644
  when:
    - not skip_docker_service_override


- name: Reload systemd daemon and restart Docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
  when:
    - not skip_docker_restart

- name: Install docker environments file
  template:
    src: docker-env.sh.j2
    dest: "/home/{{ ansible_user }}/docker-env.sh"
    backup: no
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644



